### ISSUE TITLE
syntastic support

### ISSUE THREAD

**Issue by powerman** [yoheimuta/vim-protolint#1]
Can you please make a PR to add protolint support to https://github.com/vim-syntastic/syntastic?
ALE looks promising, but syntastic is also very popular and many people get used to it.

**Comment by yoheimuta** [comment]
@powerman Thank you for your kind advice! 
It makes sense. I'll be getting to it tomorrow or weekends.

**Comment by yoheimuta** [comment]
@powerman I merged #2 to add syntactic support.
Could you give it a try?

[memo] I added this feature in this repository because the upstream appears to recommend new language support as a custom plugin.
